apiVersion: v2
name: hush-am
description: A Helm chart for Hush Security Access Management platform.
type: application
version: 0.7.0
appVersion: "v0.0.28"
home: https://hush.security
dependencies:
  - name: hush-common
    version: 0.1.0
    repository: "file://./charts/hush-common"
