apiVersion: v2
name: hush-am
description: A Helm chart for Hush Security Access Management platform.
type: application
version: 0.2.0
home: https://hush.security
dependencies:
  - name: hush-common
    version: 0.2.0
    repository: "file://./charts/hush-common"
