{{- if or .Values.hushDeployment.token .Values.hushDeployment.password -}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "hush-common.deploymentKubeSecretName" . }}
  labels: {{- include "hush-common.labels" . | nindent 4 }}
  namespace: {{ include "hush-common.namespace" . }}
data:
  {{- with .Values.hushDeployment.token }}
  deployment-token: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.hushDeployment.password }}
  deployment-password: {{ . | b64enc }}
  {{- end }}
{{- end }}
