---
hushDeployment:
  token: "ZDE6em9uZTpyZWFsbTpvcmctaWQ6ZGVwbG95bWVudC1pZA=="
  password: "koko.password"

accessManager:
  logConfig:
    default_level: info
    default_export: true
    default_export_level: warn
    loggers:
      - name: acrsyncer
        level: debug
