---
hushDeployment:
  token: "ZDE6em9uZTpyZWFsbTpvcmctaWQ6ZGVwbG95bWVudC1pZA=="
  password: "koko.password"

secretStore:
  kind: "awssm"
  aws:
    region: "eu-central-1"

containerRegistry:
  aws:
    irsa: "arn:aws:iam::000000000000:role/access-manager-iam-role"
