---
hushDeployment:
  token: "ZDE6em9uZTpyZWFsbTpvcmctaWQ6ZGVwbG95bWVudC1pZA=="
  password: "koko.password"

secretStore:
  kind: "awssm"
  aws:
    region: "eu-central-1"

image:
  pullSecret:
    name: "custom-pull-secret-name"
    username: "custom-pull-secret-username"
    password: "custom-pull-secret-password"
