---
namespaceOverride: "hush-secretless"

hushDeployment:
  token: "ZDE6em9uZTpyZWFsbTpvcmctaWQ6ZGVwbG95bWVudC1pZA=="
  password: "koko.password"

secretStore:
  kind: "kubesecrets"
  k8s:
    namespace: "hush-secretless"
