---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hush-am.accessManagerFullName" . }}
  labels: {{- include "hush-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: access-manager-service-account
  namespace: {{ include "hush-common.namespace" . }}
  {{- with (include "hush-am.accessManagerServiceAccountAnnotations" .) }}
  annotations: {{- . | nindent 4 -}}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: access-manager-common-cluster-role-binding
  labels: {{- include "hush-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: access-manager-common-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "hush-am.accessManagerFullName" . }}
    namespace: {{ include "hush-common.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "hush-am.clusterRoleFullName" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: access-manager-spire-server-cluster-role-binding
  labels: {{- include "hush-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: access-manager-spire-server-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "hush-am.accessManagerFullName" . }}
    namespace: {{ include "hush-common.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "hush-am.spireServerClusterRoleFullName" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: access-manager-spire-bundle-role-binding
  namespace: {{ include "hush-common.namespace" . }}
  labels: {{- include "hush-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: access-manager-spire-bundle-role-binding
subjects:
- kind: ServiceAccount
  name: {{ include "hush-am.accessManagerFullName" . }}
  namespace: {{ include "hush-common.namespace" . }}
roleRef:
  kind: Role
  name: {{ include "hush-am.spireBundleRoleFullName" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: access-manager-role-binding
  namespace: {{ include "hush-common.namespace" . }}
  labels: {{- include "hush-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: access-manager-role-binding
subjects:
- kind: ServiceAccount
  name: {{ include "hush-am.accessManagerFullName" . }}
  namespace: {{ include "hush-common.namespace" . }}
roleRef:
  kind: Role
  name: {{ include "hush-am.accessManagerFullName" . }}
  apiGroup: rbac.authorization.k8s.io
