{{- if not .Values.accessManager.priorityClassName -}}
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "hush-am.accessManagerFullName" . }}
  labels: {{- include "hush-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: access-manager-priority-class
value: {{ int .Values.accessManager.priority }}
globalDefault: false
preemptionPolicy: "PreemptLowerPriority"
description: "Priority class for Hush Access Manager pods."
{{- end }}
