---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hush-am.accessManagerFullName" . }}
  labels: {{- include "hush-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: access-manager-service
  namespace: {{ include "hush-common.namespace" . }}
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  selector: {{- include "hush-common.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: access-manager
  ports:
    - name: spire
      protocol: TCP
      port: {{ .Values.spireServer.port }}
    - name: rest
      protocol: TCP
      port: {{ .Values.manager.port }}
    - name: admission
      protocol: TCP
      port: {{ .Values.admissionController.port }}
