{{- $kind := (include "hush-am.managerKind" .) -}}
---
apiVersion: apps/v1
{{- if eq $kind "statefulset" }}
kind: StatefulSet
{{- else }}
kind: Deployment
{{- end }}
metadata:
  name: {{ include "hush-am.accessManagerFullName" . }}
  labels: {{- include "hush-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: manager
  namespace: {{ include "hush-common.namespace" . }}

spec:
  selector:
    matchLabels: {{- include "hush-common.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: manager
  replicas: {{ .Values.manager.replicas }}
  {{- if eq $kind "statefulset" }}
  serviceName: {{ include "hush-am.accessManagerFullName" . }}
  updateStrategy:
    type: RollingUpdate
  {{- else }}
  strategy:
    type: RollingUpdate
  {{- end }}
  minReadySeconds: 10

  template:
    metadata:
      labels: {{- include "hush-common.labels" . | nindent 8 }}
        app.kubernetes.io/component: manager
      {{ with .Values.manager.annotations -}}
      annotations: {{- . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.manager.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.manager.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.manager.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (include "hush-am.managerAffinity" . | fromYaml) }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      hostNetwork: {{ include "hush-am.managerHostNetwork" . }}
      dnsPolicy: {{ include "hush-am.managerDnsPolicy" . }}
      restartPolicy: Always
      {{- with (include "hush-am.kubeImagePullSecretEffectiveList" .) }}
      imagePullSecrets: {{- . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.manager.terminationGracePeriodSeconds }}
      serviceAccountName: {{ include "hush-am.accessManagerFullName" . }}
      initContainers:
        - name: secretless-manager-init
          image: {{ include "hush-am.accessManagerImagePath" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: spire-server-socket-dir
              mountPath: {{ include "hush-am.spireServerSocketDirMountPath" . }}
            - name: data-volume
              mountPath: {{ include "hush-am.dataVolumeMountPath" . }}
          command: ["/bin/bash", "-xc"]
          args:
            - |
              mkdir -p {{ include "hush-am.spireServerDataDirPath" . }}
              chown -R 1000:1000 {{ include "hush-am.spireServerDataDirPath" . }}
              mkdir -p {{ include "hush-am.spireServerSocketDirPath" . }}
              chown -R 1000:1000 {{ include "hush-am.spireServerSocketDirPath" . }}
              mkdir -p {{ include "hush-am.managerDataDirPath" . }}
              mkdir -p {{ include "hush-am.spireServerLogDirMountPath" . }}
              chown 1000:1000 {{ include "hush-am.spireServerLogDirMountPath" . }}
              . /usr/local/bin/hdc.sh
              /mufasa init
          env:
            {{- include "hush-am.managerEnvs" . | nindent 12 }}
          securityContext:
            runAsUser: 0
            runAsGroup: 0
        - name: admission-controller-init
          image: {{ include "hush-am.admissionControllerImagePath" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: data-volume
              mountPath: {{ include "hush-am.dataVolumeMountPath" . }}
          command: ["/bin/bash", "-xc"]
          args:
            - |
              mkdir -p {{ include "hush-am.admissionControllerDataDirPath" . }}
              openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:P-256 -out {{ include "hush-am.admissionControllerDataDirPath" . }}/tls.key
              openssl req -x509 -key {{ include "hush-am.admissionControllerDataDirPath" . }}/tls.key \
                -out {{ include "hush-am.admissionControllerDataDirPath" . }}/tls.crt \
                -sha256 -days 3650 \
                -CA /opt/zazu/zazu-root.crt -CAkey /opt/zazu/zazu-root.key \
                -subj "/CN=zazu" \
                -addext "basicConstraints=critical,CA:FALSE" \
                -addext "keyUsage=digitalSignature" \
                -addext "extendedKeyUsage=serverAuth" \
                -addext "subjectAltName={{ include "hush-am.managerServiceAltNames" . }}"
              openssl x509 -in {{ include "hush-am.admissionControllerDataDirPath" . }}/tls.crt -noout -text
          securityContext:
            runAsUser: 0
            runAsGroup: 0
      containers:
        - name: spire-server
          image: {{ include "hush-am.spireServerImagePath" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with and .Values.manager .Values.manager.spireServerResources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            exec:
              command:
                - /opt/spire/bin/spire-server
                - healthcheck
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            exec:
              command:
                - /opt/spire/bin/spire-server
                - healthcheck
            failureThreshold: 12
            periodSeconds: 10
          volumeMounts:
            - name: spire-server-socket-dir
              mountPath: {{ include "hush-am.spireServerSocketDirMountPath" . }}
            - name: data-volume
              mountPath: {{ include "hush-am.dataVolumeMountPath" . }}
            - name: spire-server-log-dir
              mountPath: {{ include "hush-am.spireServerLogDirMountPath" . }}
          env:
            {{- include "hush-am.mandatoryEnvs" . | nindent 12 }}
            {{- include "hush-am.siloEnvs" . | nindent 12 }}
            - name: AUTH_PLUGIN_KEY_DB_PATH
              value: {{ include "hush-am.keyDbFilePath" . }}
            - name: MUFASA_SPIRE_SERVER_PORT
              value: {{ .Values.spireServer.port | quote }}
        - name: secretless-manager
          image: {{ include "hush-am.accessManagerImagePath" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with and .Values.manager .Values.manager.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: vector-socket-dir
              mountPath: /tmp/vector
            - name: spire-server-socket-dir
              mountPath: {{ include "hush-am.spireServerSocketDirMountPath" . }}
            - name: spire-agent-socket-dir
              mountPath: {{ include "hush-am.spireAgentSocketDirMountPath" . }}
            - name: data-volume
              mountPath: {{ include "hush-am.dataVolumeMountPath" . }}
          env:
            {{- include "hush-am.managerEnvs" . | nindent 12 }}
        - name: admission-controller
          image: {{ include "hush-am.admissionControllerImagePath" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with and .Values.admissionController .Values.admissionController.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: vector-socket-dir
              mountPath: /tmp/vector
            - name: data-volume
              mountPath: {{ include "hush-am.dataVolumeMountPath" . }}
              readOnly: true
          env:
            {{- include "hush-am.mandatoryEnvs" . | nindent 12 }}
            - name: MUFASA_INJECTOR_IMAGE
              value: {{ include "hush-am.injectorImagePath" . }}
            - name: ZAZU_CERT_FILE_PATH
              value: {{ include "hush-am.admissionControllerDataDirPath" . }}/tls.crt
            - name: ZAZU_KEY_FILE_PATH
              value: {{ include "hush-am.admissionControllerDataDirPath" . }}/tls.key
            - name: MUFASA_POLICY_DB_PATH
              value: {{ include "hush-am.policyDbFilePath" . }}
            - name: MUFASA_SPIRE_AGENT_HOST_DIR
              value: {{ .Values.spireAgent.hostDir }}
            - name: MUFASA_SPIRE_AGENT_HOST_DIR_MOUNT_PATH
              value: {{ include "hush-am.spireAgentSocketDirMountPath" . }}
            - name: MUFASA_SPIRE_AGENT_SOCKET_PATH
              value: {{ include "hush-am.spireAgentSocketPath" . }}
            - name: MUFASA_REST_SERVER_ADDRESS
              value: {{ include "hush-am.managerRestAddress" . }}
            - name: MUFASA_INJECTOR_IMAGE_PULL_POLICY
              value: {{ include "hush-am.injectorImagePullPolicy" . }}
            {{- with .Values.containerRegistry.default }}
            - name: ZAZU_DEFAULT_REGISTRY
              value: {{ . | quote }}
            {{- end }}
            - name: ZAZU_MUTATION_TIMEOUT
              value: "{{ .Values.admissionController.mutatingWebhookTimeout }}s"
            {{- if .Values.admissionController.verboseInjector }}
            - name: ZAZU_VERBOSE_INJECTOR
              value: "true"
            {{- end }}
            - name: ZAZU_BIND_ADDRESS
              value: {{ include "hush-am.admissionControllerBindAddress" . | quote }}
            - name: ZAZU_AWS_ECR_CFG_MODE
              value: {{ include "hush-am.admissionControllerAwcEcrCfgMode" . | quote }}
        - name: vector
          image: {{ include "hush-am.accessManagerVectorImagePath" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with and .Values.manager .Values.manager.vectorResources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: vector-socket-dir
              mountPath: /tmp/vector
            - name: data-volume
              mountPath: {{ include "hush-am.dataVolumeMountPath" . }}
              readOnly: true
            - name: spire-server-log-dir
              mountPath: {{ include "hush-am.spireServerLogDirMountPath" . }}
          env:
            {{- include "hush-am.mandatoryEnvs" . | nindent 12 }}
            {{- with (include "hush-am.effectiveDeploymentPasswordKubeSecretRef" . | fromYaml) }}
            - name: DEPLOYMENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}
                  key: {{ .key }}
            {{- end }}
            - name: REPORT_SUBSYSTEM_NAME
              value: "mufasa"
            - name: REPORT_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            {{- with .Values.eventReportingConsole }}
            - name: EVENT_REPORTING_CONSOLE
              value: {{ . | quote }}
            {{- end }}
            - name: HELM_RELEASE
              value: {{ .Release.Name }}
            - name: HELM_NAMESPACE
              value: {{ include "hush-common.namespace" . }}
            - name: HELM_CHART_VERSION
              value: {{ .Chart.Version | quote }}
      volumes:
        {{- if eq $kind "deployment" }}
        - name: data-volume
          emptyDir: {}
        {{- end }}
        - name: vector-socket-dir
          emptyDir:
            sizeLimit: 1Mi
        - name: spire-server-socket-dir
          emptyDir:
            sizeLimit: 1Mi
        - name: spire-agent-socket-dir
          hostPath:
            path: {{ .Values.spireAgent.hostDir }}
            type: DirectoryOrCreate
        - name: spire-server-log-dir
          emptyDir: {}
  {{- if eq $kind "statefulset" }}
  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        {{- with .Values.manager.dataVolumeClaim.selector }}
        selector: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.manager.dataVolumeClaim.accessModes }}
        accessModes: {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.manager.dataVolumeClaim.size }}
        {{- with .Values.manager.dataVolumeClaim.storageClassName }}
        storageClassName: {{ . | quote }}
        {{- end }}
        {{- with .Values.manager.dataVolumeClaim.volumeName }}
        volumeName: {{ . | quote }}
        {{- end }}
  {{- end }}
