{{- if not .Values.spireAgent.priorityClassName -}}
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "hush-am.spireAgentFullName" . }}
  labels: {{- include "hush-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: spire-agent-priority-class
value: {{ int .Values.spireAgent.priority }}
globalDefault: false
preemptionPolicy: "PreemptLowerPriority"
description: "Priority class for Hush Access Management Spire Agent pods."
{{- end }}
