---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hush-am.spireBundleConfigMapName" . }}
  namespace: {{ include "hush-common.namespace" . }}
  labels: {{- include "hush-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: spire-bundle-config-map
