---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hush-am.spireAgentFullName" . }}
  labels: {{- include "hush-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: spire-agent-service-account
  namespace: {{ include "hush-common.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spire-agent-common-cluster-role-binding
  labels: {{- include "hush-common.labels" . | nindent 4 }}
    app.kubernetes.io/component: spire-agent-common-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "hush-am.spireAgentFullName" . }}
    namespace: {{ include "hush-common.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "hush-am.clusterRoleFullName" . }}
  apiGroup: rbac.authorization.k8s.io
