{{- define "hush-common.deploymentSecret" -}}
{{- if (include "hush-common.shouldCreateDeploymentKubeSecret" .) -}}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "hush-common.deploymentKubeSecretName" . }}
  labels: {{- include "hush-common.labels" . | nindent 4 }}
  namespace: {{ include "hush-common.namespace" . }}
data:
  {{- if (include "hush-common.shouldCreateDeploymentTokenKubeSecret" .) }}
  deployment-token: {{ (include "hush-common.getDeploymentTokenValue" .) | b64enc }}
  {{- end }}
  {{- if (include "hush-common.shouldCreateDeploymentPasswordKubeSecret" .) }}
  deployment-password: {{ (include "hush-common.getDeploymentPasswordValue" .) | b64enc }}
  {{- end }}
{{- end -}}
{{- end -}}
