{{- define "hush-common.imagePullSecret" -}}
{{- if (include "hush-common.shouldCreateKubeImagePullSecret" .) -}}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "hush-common.kubeImagePullSecretName" . }}
  labels: {{- include "hush-common.labels" . | nindent 4 }}
  namespace: {{ include "hush-common.namespace" . }}
data:
  .dockerconfigjson: {{ include "hush-common.kubeImagePullSecretData" . | quote }}
{{- end -}}
{{- end -}}
