---
hushDeployment:
  token: "ZDE6em9uZTpyZWFsbTpvcmctaWQ6ZGVwbG95bWVudC1pZA=="
  password: "koko.password"

secretStore:
  kind: "kubesecrets"

containerRegistry:
  aws:
    irsa: "arn:aws:iam::000000000000:role/secretless-manager-iam-role"
