---
hushDeployment:
  secretKeyRef:
    name: "pre-existing-secret-name"
    key: "password-key-name"
    tokenKey: "token-key-name"

secretStore:
  kind: "awssm"
  aws:
    region: "eu-central-1"

containerRegistry:
  aws:
    access:
      irsa: "arn:aws:iam::000000000000:role/secretless-manager-iam-role"
